language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
# install:
#  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "tech-overlord-github"

script:
  - sonar-scanner
  - pip install psutil
  - cd $TRAVIS_BUILD_DIR
  - python sysmonitoring.py